[package]
name = "gbnf-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
gbnf-core = { path = "../gbnf-core" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
