[package]
name = "gbnf"
version = "0.1.0"
edition = "2024"

[dependencies]
gbnf-core = { path = "../gbnf-core" }
gbnf-macro = { path = "../gbnf-macro" }
serde_json = "1"
jsonschema = "0.41.0"

[dev-dependencies]
insta = "1.46.1"
