[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "nobodywho-python"
version = "0.1.0"
description = "Python bindings for nobodywho"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.1",
    "pytest-stub>=1.1.0",
]

[tool.maturin]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]
module-name = "nobodywho"

[dependency-groups]
dev = ["pytest>=9.0.1", "pytest-asyncio>=1.3.0"]
